### ISSUE TITLE
Less-aggressive pattern?

### ISSUE THREAD

**Issue by rking** [yyclaw/rails_emoji#1]
I noticed the pattern is:

```
 /:([a-z0-9_\-\+]+):/
```

That is going to make a mess if any technical data is processed by the gem. For example, a Ruby backtrace would attempt to sub in emojicons for line numbers.

Also, you don't have to backslash quite so much.

I propose:

```
/(?:^|\s):([a-z0-9_+-]+):(?:$|\s)/
```

What do you think?
—☈

**Comment by yyclaw** [comment]
Thanks for your issue!

Your regex pattern does not matches the `:a:` of `:a:b:` .

I will remove three number-icons: `:109:`, `:100:`, `:1234:` .

You can upgrade to v1.6.1.

And, all the emojis are in http://www.emoji-cheat-sheet.com/
