### ISSUE TITLE
Rails production mode?

### ISSUE THREAD

**Issue by siegy22** [yyclaw/rails_emoji#6]
Hi there.. it seems that the emojis are not found in production mode?

Is this a bug or am I doing something wrong with rails?

**Comment by woodmanzee** [comment]
@Elektron1c97 did you ever find the reason for this? I'm having the same issue right now

**Comment by siegy22** [comment]
@woodmanzee 
I would recommend using https://github.com/github/gemoji I think this gem is no longer supported/monitored.
